POST http://localhost:5001/api/users/checktoken
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjhiM2IyOThiOGE1Yzk5ZjQzMjRjZmMiLCJuYW1lIjoiTG9uZyIsImVtYWlsIjoibG9uZy5kZW5AdGVzdC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NTMyOTIwMzgsImV4cCI6MTY1MzM3ODQzOH0._76X26rhZzsRLvhO1FTrLxPYttVh8ZeI-6R3EDHZzlg

###


POST http://localhost:5001/api/users/signin
Content-Type: application/json

{
    "email":"long.den@test.com",
    "password":"long1234"
}

###
GET http://localhost:5001/api/users/seed